//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUpSchoolProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutID { get; set; }
        public string NameSurname { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual TblAbout TblAbout1 { get; set; }
        public virtual TblAbout TblAbout2 { get; set; }
        public virtual TblMember TblMember { get; set; }
    }
}
