//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUpSchoolProject.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLanguage
    {
        public int LanguageID { get; set; }
        public string LanguageName { get; set; }
        public string LanguageLevel { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual TblLanguage TblLanguage1 { get; set; }
        public virtual TblLanguage TblLanguage2 { get; set; }
        public virtual TblMember TblMember { get; set; }
    }
}
